#!/usr/bin/env bash

## Cursor active at boot
xsetroot -cursor_name left_ptr &

## Restore Wallpaper
#~/.fehbg &
nitrogen --restore &

## Polkit agent
lxsession &

## Enable power management
exec xfce4-power-manager &

## Start Compositing Manager
exec picom --experimental-backends --config $HOME/.xmonad/picom-02.conf &

## Notification Daemon
exec dunst &
#/usr/lib/xfce4/notifyd/xfce4-notifyd &

## File Manager Daemon
thunar --daemon &
#exec pcmanfm -d &

## Set keyboard layout
setxkbmap us -variant altgr-intl &

## Turn ON numlock key
numlockx on &

## Run on boot other services
udiskie &
