#! /bin/sh

killall variety
killall volumeicon

xsetroot -cursor_name left_ptr &
setxkbmap -layout us -variant altgr-intl &
#/usr/bin/lxpolkit &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
udiskie &
xfce4-notifyd &
xfce4-power-manager &
picom &
variety &
flameshot &
volumeicon &
nm-applet &
thunar --daemon &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a discord desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
