# Don't print a new line at the start of the prompt
add_newline = false 

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[username]
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "@[$hostname](bold green) in "
trim_at = ".companyname.com"
disabled = false

[directory]
truncation_length = 8
truncation_symbol = "…/"

[cmd_duration]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
