"$schema" = 'https://starship.rs/config-schema.json'

format = "[$directory$git_branch$git_status]($style)$character"

right_format = "[$cmd_duration$time]($style)"

directory = { truncation_length = 2 }

character = { success_symbol = "[>](bold green)", error_symbol = "[✗](bold red)" }

time = { disabled = false, format = "[$time]($style)", style = "dimmed" }
